### PR TITLE
Add the logo to the page header

### PR DESCRIPTION
**Pull request by birdcar**
Hi @ginnyfahs 👋 

My name is Nick and I work on the GitHub Support team. 

This PR adds the logo to Cayman's page header. I went with the `svg` logo rather than the `png` file, but I can absolutely change that if you'd prefer. 

Additionally, I moved the image files into an `img` directy inside the `assets` directory.

### CODE REVIEW

**Comment by triketora** [comment]
Hi! The logo is great but page header looks a little redundant with this change:

screen shot 2018-03-07 at 4 30 48 pm

How about doing something like this instead?

screen shot 2018-03-07 at 4 34 18 pm

In `_layouts/default.html`:
```
-      <img src="assets/img/movingforward-logo.svg" alt="MovingForward Logo">
-      <h1 class="project-name">{{ site.title | default: site.github.repository_name }}</h1>
+      <h1 class="project-name">Project <img src="assets/img/movingforward-logo.svg" alt="MovingForward Logo"></h1>
```

In `_sass/jekyll-theme-cayman.scss`:
```
.project-name {
+
+  img {
+    vertical-align: middle;
+  }
}
```

(I haven't worked with Jekyll / themes like this before so I don't know the right place to make the CSS change, maybe it is better to set custom styles elsewhere to override the defaults?)

**Comment by birdcar** [comment]
> The logo is great but page header looks a little redundant with this change

@triketora Definitely agree, I just didn't want to presume to make a stylistic decision on my own since I was merely helping with a ticket the GitHub Support team received. 🙇

I'll go ahead and make those changes. 

> (I haven't worked with Jekyll / themes like this before so I don't know the right place to make the CSS change, maybe it is better to set custom styles elsewhere to override the defaults?)

It's generally a best practice to make changes like that to the `assets/styles.scss` file rather than the theme itself, though either is acceptable. For now, I'll work with the `assets/styles.scss` file.

**Comment by triketora** [comment]
Thanks @nickcannariato! Sorry for the back and forth, but just chatted with the team, and we think it's better to just drop the "Project" altogether. So, fewer changes required! Can you keep it at your original diff, but remove the `<h1>` tag? Thank you so much!

**Comment by birdcar** [comment]
> Sorry for the back and forth, but just chatted with the team, and we think it's better to just drop the "Project" altogether. So, fewer changes required! Can you keep it at your original diff, but remove the \<h1> tag? Thank you so much!

@triketora No problem at all! You _just_ missed my committing those changes though. 😆 

Before I make that final change, the only question I have is how large would you like the logo? `min-width: 50%` would be my gut instinct, but I'm very much not a designer 🙈

**Comment by triketora** [comment]
Checking with designer -- it'll be a couple hours before she can get the exact specs for different screen sizes. 

Btw, you are now known as "helpful github angel" within our team 😇

**Comment by triketora** [comment]
This is great -- let's just merge what you have here and I'll do more CSS fiddly stuff on my end. Thanks for the tip on using `assets/styles.scss`.

**Pull request merged**
